import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import TopAppBar from '../components/appBar'
import ResponsiveDrawer from '../components/responsiveDrawer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ResponsiveDrawer></ResponsiveDrawer>
      </main>
    </div>
  )
}

export default Home
23
